### ISSUE TITLE
Crystal conversions

### ISSUE THREAD

**Issue by alexanderadam** [synvert-hq/synvert-snippets-ruby#276]
I just saw [your comment](https://github.com/OrelSokolov/crystalize/issues/2#issuecomment-1164779555).

And now I'm curious: did you start adding Crystal snippets too? :thinking:

**Comment by flyerhzm** [comment]
@alexanderadam I haven't started yet and I don't have any experience with Crystal yet.

If you're interested, I can help you get started with writing a snippet.

Generally, the snippet performs a find-and-replace function. You can specify the rule for what code to find and what it should be replaced with, and then I can guide you on how to write the snippet.
