### ISSUE TITLE
wouldn't use_proc_to_symbol be more useful than use_symbol_to_proc?

### ISSUE THREAD

**Issue by breathe** [synvert-hq/synvert-snippets-ruby#35]
I'm checking out synvert to see about adding codegen to my rails app.

Interesting project -- I'm curious why you have the use_symbol_to_proc snippet but not the reverse use_proc_to_symbol ...?

It seems like the reverse transformation would be more useful -- &:to_s is easy to write, hard to extend when you realize you need some additional logic, whereas the other form is easier to read and edit but annoying to type ...

It feels to me like the better path for a snippet like this would be the exact opposite of the transformation implemented ...  I'd like to allow typing the shorthand syntax but -- convert that on file save to the more easily editable form for subsequent development ...

**Comment by flyerhzm** [comment]
@breathe yes, feel free to create a PR to add use_proc_to_symbol snippet
